### ISSUE TITLE
Remove duplicated ternary operator

### ISSUE THREAD

**Issue by kresimir-coko** [Rinakat225/Todo-list#10]
https://github.com/Rinakat225/Todo-list/blob/9425613facb42840182d01162eea3856be179630/src/App.js#L109-L118

Rendering empty strings as a fallback is an [anti-pattern](https://en.wikipedia.org/wiki/Anti-pattern), rather use `&&` and use a different technique to render a fallback, maybe a sanity check before the main return that returns an empty fragment

**Comment by katarina-cala** [comment]
Done on commit: https://github.com/Rinakat225/Todo-list/commit/3931dc3578d7f9adbb5c8ac6d62fd3d6dffb975f
