### ISSUE TITLE
Clean code pt. 1 - avoid leading or trailing empty spaces

### ISSUE THREAD

**Issue by kresimir-coko** [Rinakat225/Todo-list#11]
https://github.com/Rinakat225/Todo-list/blob/9425613facb42840182d01162eea3856be179630/src/App.js#L84

We have more occurrences of the same thing

**Comment by katarina-cala** [comment]
Done on commit: https://github.com/Rinakat225/Todo-list/commit/1eb57e35bb63cd14dafac2a554cf073e2d5ffba0
