### ISSUE TITLE
Add the ability to tag each todo, both while being created, and after it's already been created

### ISSUE THREAD

**Issue by kresimir-coko** [Rinakat225/Todo-list#16]
User should have the option to add a custom tag to each todo. 
Investigate how best to allow the user to add these tags - maybe by typing a `#` followed by the tag, or as an option when editing the todo, etc.

Inspiration:

![image](https://github.com/Rinakat225/Todo-list/assets/24564752/b13971d7-12bb-43c1-83fe-f24f3b95b2c9)

![image](https://github.com/Rinakat225/Todo-list/assets/24564752/27a7821f-86fa-4a28-bdae-d5d7a2cbc3ce)

**Comment by katarina-cala** [comment]
Done on commit: https://github.com/Rinakat225/Todo-list/commit/c4a86ab189383e2ce9db44ab31037d01fa30d37f
