### ISSUE TITLE
Each todo should have an option to have "due date" field

### ISSUE THREAD

**Issue by kresimir-coko** [Rinakat225/Todo-list#17]
A "due date", or a reminder (maybe just due date for simplicity's sake) should be available for all todos, and the chosen datetime should be shown in the todo list, maybe even sortable by urgency

**Comment by katarina-cala** [comment]
"due date" added on commit: https://github.com/Rinakat225/Todo-list/commit/5f8aef5b995f918972afe568458d72c8aa9536f4 
/ "sortability by urgency" -> wip
