### ISSUE TITLE
Entire button should be clickable, not just the icon

### ISSUE THREAD

**Issue by kresimir-coko** [Rinakat225/Todo-list#18]
In this example, the delete, edit and complete buttons - only icons are clickable, not the entire button (the gray backgrund around the icon)

Also, add some changes on hover, so the user knows when they are hovering interactive elements

![image](https://github.com/Rinakat225/Todo-list/assets/24564752/f8f8a75d-e8c6-48ab-8f61-190fb1c2d8ba)

**Comment by katarina-cala** [comment]
"Entire button clickable" done on commit: https://github.com/Rinakat225/Todo-list/commit/295e8b19bf2973e2984f6f8d7c37ee9039e53b27 
"Hover effect" done on commit: https://github.com/Rinakat225/Todo-list/commit/1877a0ab058f9be6184a6fae7e4f68ea0034f1d1
