### ISSUE TITLE
Add the ability for the user to switch between light and dark mode

### ISSUE THREAD

**Issue by kresimir-coko** [Rinakat225/Todo-list#6]
Somewhere in the UI add a button that allows switching between light and dark mode.

Use Tailwind's `dark` variant - https://tailwindcss.com/docs/dark-mode

**Comment by katarina-cala** [comment]
Done on commit: https://github.com/Rinakat225/Todo-list/commit/c29c5983e3f35b8c8e4733a55bdff98d5f65f4a6
