### ISSUE TITLE
Remove unused classNames function and investigate using tailwind-merge

### ISSUE THREAD

**Issue by kresimir-coko** [Rinakat225/Todo-list#7]
https://github.com/Rinakat225/Todo-list/blob/9425613facb42840182d01162eea3856be179630/src/App.js#L7-L9

tailwind-merge -> https://www.npmjs.com/package/tailwind-merge

**Comment by katarina-cala** [comment]
Done on commit: https://github.com/Rinakat225/Todo-list/commit/4d620d027cb12b13c7776a5eccf9cf3c78fe0764
