### ISSUE TITLE
Investigate using react-inlinesvg to streamline usage of SVG icons

### ISSUE THREAD

**Issue by kresimir-coko** [Rinakat225/Todo-list#9]
https://github.com/Rinakat225/Todo-list/blob/9425613facb42840182d01162eea3856be179630/src/App.js#L85-L98

react-inlinesvg => https://www.npmjs.com/package/react-inlinesvg

Alternatively, use some other technique to avoid having SVGs hardcoded like the above example

**Comment by katarina-cala** [comment]
Done with Heroicons library on commit: https://github.com/Rinakat225/Todo-list/commit/99959a6a32b87620c1a5e6b37ef85361a3861ed8
